kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.hub.docker.com
      repo: registry.hub.docker.com/tyleragostino/spinnyboi
      tags: latest
      cache_from: "registry.hub.docker.com/tyleragostino/spinnyboi:latest"
    when:
      branch:
        - main
      changeset:
        includes: [ "**/**.py", "**/**.txt", "**/Dockerfile" ]
  - name: deploy
    image: plugins/webhook
    settings:
      urls: http://192.168.1.125:9996/api/stacks/webhooks/81cacdd6-d5ef-45cd-9983-cd3ff1f1058b
    when:
      changeset:
        includes: [ "**/**.py", "**/**.txt", "**/docker_compose.yaml", "**/Dockerfile"  ]

trigger:
  ref:
    - refs/heads/main
