kind: pipeline
name: default
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tyleragostino/spinnyboi
      tags: latest

trigger:
  ref:
    - refs/heads/main
