version: "3.9"
services:
  spinnyboi:
    image: tyleragostino/spinnyboi:latest
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GSHEET_ID=${GSHEET_ID}
  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
        - ollama:/root/.ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    ports:
      - 3004:8080
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.1.125:11434'
    restart: always

volumes:
  ollama:
  open-webui: