version: '3.9'
services:
  spinnyboi:
    image: tyleragostino/spinnyboi:latest
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GSHEET_ID=${GSHEET_ID}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=spinnyboi
      - DATABASE_URL=sqlite:///data/spinny.db
      - IRACING_EMAIL=${IRACING_EMAIL}
      - IRACING_PASSWORD=${IRACING_PASSWORD}
      - IRACING_CLIENT_ID=${IRACING_CLIENT_ID}
      - IRACING_CLIENT_SECRET=${IRACING_CLIENT_SECRET}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - REGISTRATION_SHEET_ID=${REGISTRATION_SHEET_ID}
      - ATTENDANCE_SHEET_ID=${ATTENDANCE_SHEET_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - spinny_db:/app/data
      - /mnt/user/apollo-share/Fonts:/usr/share/fonts/
    dns:
      - 1.1.1.1

volumes:
  spinny_db:
